version: '3.8'

services:
  celery-worker-parsing:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A frameworks_and_drivers.django.parsing.celery_app worker --loglevel=debug
    volumes:
      - .:/app
    env_file:
      - environments/db.env
      - environments/web.env
      - environments/minio.env

  celery-beat-parsing:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A frameworks_and_drivers.django.parsing.celery_app beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=debug
    volumes:
      - .:/app
    env_file:
      - environments/db.env
      - environments/web.env
      - environments/minio.env

  # flower:
  #   image: mher/flower
  #   restart: always
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - .:/code
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - FLOWER_PORT=9090
  #   depends_on:
  #     - celery-worker-parsing

volumes:
  postgres_data:
  minio_data:

networks:
  default:
    external:
      name: afisha
