version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - environments/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web-parsing:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python src/frameworks_and_drivers/django/parsing/manage.py migrate &&
             python src/frameworks_and_drivers/django/parsing/manage.py collectstatic --noinput && 
             python src/frameworks_and_drivers/django/parsing/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: web
    depends_on:
      - db
    env_file:
      - environments/db.env
      - environments/web.env
      - environments/minio.env
      - environments/tg.env

  celery-worker-parsing:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A frameworks_and_drivers.django.parsing.celery_app worker --loglevel=debug
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - environments/db.env
      - environments/web.env
      - environments/minio.env

  celery-beat-parsing:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A frameworks_and_drivers.django.parsing.celery_app beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=debug
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - environments/db.env
      - environments/web.env
      - environments/minio.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-06-06T09-36-42Z
    hostname: "minio"
    restart: always
    volumes:
      - minio_data:/minio_files:Z
    env_file:
      - environments/minio.env
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  create_buckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - environments/minio.env
    entrypoint: "bash -c \"/usr/bin/mc config host add myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_USER}; /usr/bin/mc mb --quiet myminio/$${MINIO_BUCKET_NAME}; /usr/bin/mc anonymous set public myminio/$${MINIO_BUCKET_NAME}\""


volumes:
  postgres_data:
  minio_data:

networks:
  default:
    external:
      name: afisha
