# Generated by Django 4.2 on 2025-02-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_manager", "0003_remove_tags_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="unique_id",
            field=models.CharField(
                default="test", editable=False, max_length=250, unique=True
            ),
            preserve_default=False,
        ),
    ]
